# Buildpacks to include in builder
[[buildpacks]]
uri = "buildpack/mkdocs-buildpack"

[[buildpacks]]
uri = "buildpack/sphynx-buildpack"

[[buildpacks]]
uri = "buildpack/mkdocs-az-buildpack"

# Order used for detection
[[order]]
[[order.group]]
id = "applaudo/mkdocs"
version = "0.0.1"

[[order]]
[[order.group]]
id = "applaudo/sphynx"
version = "0.0.1"

[[order]]
[[order.group]]
id = "applaudo/mkdocsaz"
version = "0.0.1"

# Stack that will be used by the builder
[stack]
id = "io.buildpacks.applaudo.stacks.focal"
# This image is used at runtime
run-image = "cnbs/applaudo-stack-run:focal"
# This image is used at build-time
build-image = "cnbs/applaudo-stack-build:focal"