VERSION 0.6
FROM ubuntu:focal
WORKDIR /docs-workdir

build:
   FROM ubuntu:focal
   RUN apt-get update && apt-get install -y python3 python3-pip && rm -rf /var/lib/apt/lists/*
   RUN pip install --no-cache-dir --upgrade pip && pip install --no-cache-dir mkdocs

   RUN mkdir /server/
   RUN cd /server
   WORKDIR /server
   COPY mkdocs-sample/docs ./docs
   COPY mkdocs-sample/mkdocs.yml ./mkdocs.yml
   RUN mkdocs build
   SAVE ARTIFACT site /site

deployment:
   FROM ubuntu:focal
   RUN apt-get update && apt-get install -y git wget jq tar lsb-release && rm -rf /var/lib/apt/lists/*

   ARG DEBIAN_FRONTEND=noninteractive

   RUN wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb" &&  \
     dpkg -i packages-microsoft-prod.deb && \
     apt-get update && \
     apt-get install -y powershell

   RUN mkdir /deployment/
   WORKDIR /deployment
   RUN ls
   RUN wget https://aka.ms/downloadazcopy-v10-linux
   RUN mkdir azcopy-exec
   RUN tar -xzvf downloadazcopy-v10-linux -C ./azcopy-exec
   RUN ls
   RUN --no-cache chmod +x azcopy-exec/azcopy_linux_amd64_10.17.0/azcopy
   RUN cp azcopy-exec/azcopy_linux_amd64_10.17.0/azcopy /usr/local/bin/
   COPY +build/site site
   ARG DEPLOYMENT_BLOB_SERVICE_URL
   ARG DEPLOYMENT_SITE_DIRECTORY
   ARG SAS_TOKEN
   WORKDIR /deployment
   RUN --no-cache pwd
   COPY deploy.sh deploy.sh
   RUN chmod +x deploy.sh
   RUN --no-cache ls
   WORKDIR /deployment/site
   RUN --no-cache ls
   WORKDIR /deployment
   RUN echo "$DEPLOYMENT_BLOB_SERVICE_URL\$web$SAS_TOKEN"
   CP
   RUN --no-cache ./deploy.sh

all:
   BUILD +build
   BUILD +deployment